/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

import javax.swing.JOptionPane;

/**
 *
 * @author arzate
 */
public class Pantalla extends javax.swing.JFrame {

    double acumulado=0.0;
    String entradaActual="";
    String operador="";
    boolean bandera=false;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
            configurarTeclado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btn_c = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_multiplicacion = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_resultado = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        txt_Visor = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btn_c.setText("C");
        btn_c.addActionListener(this::btn_cActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_c, gridBagConstraints);

        btn_division.setText("/");
        btn_division.addActionListener(this::btn_divisionActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_division, gridBagConstraints);

        btn_multiplicacion.setText("X");
        btn_multiplicacion.addActionListener(this::btn_multiplicacionActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_multiplicacion, gridBagConstraints);

        btn_resta.setText("-");
        btn_resta.addActionListener(this::btn_restaActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_resta, gridBagConstraints);

        btn_4.setText("4");
        btn_4.addActionListener(this::btn_4ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_4, gridBagConstraints);

        btn_5.setText("5");
        btn_5.addActionListener(this::btn_5ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_5, gridBagConstraints);

        btn_6.setText("6");
        btn_6.addActionListener(this::btn_6ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_6, gridBagConstraints);

        btn_9.setText("9");
        btn_9.addActionListener(this::btn_9ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_9, gridBagConstraints);

        btn_8.setText("8");
        btn_8.addActionListener(this::btn_8ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_8, gridBagConstraints);

        btn_7.setText("7");
        btn_7.addActionListener(this::btn_7ActionPerformed);
        btn_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_7KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_7, gridBagConstraints);

        btn_suma.setText("+");
        btn_suma.addActionListener(this::btn_sumaActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_suma, gridBagConstraints);

        btn_1.setText("1");
        btn_1.addActionListener(this::btn_1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_1, gridBagConstraints);

        btn_2.setText("2");
        btn_2.addActionListener(this::btn_2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_2, gridBagConstraints);

        btn_3.setText("3");
        btn_3.addActionListener(this::btn_3ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_3, gridBagConstraints);

        btn_resultado.setText("=");
        btn_resultado.addActionListener(this::btn_resultadoActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_resultado, gridBagConstraints);

        btn_0.setText("0");
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.addActionListener(this::btn_0ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btn_0, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 480, 640));

        txt_Visor.setBackground(new java.awt.Color(255, 255, 255));
        txt_Visor.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        txt_Visor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_Visor.setOpaque(true);
        getContentPane().add(txt_Visor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 410, 76));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoCalc.jpg"))); // NOI18N
        fondo.setText(" ");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        txt_Visor.setText("");
    double acumulado=0.0;
    String entradaActual="";
    String operador="";
    boolean bandera=false;
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
      
        procesarNumero("7");
        
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed

       procesarNumero("8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed

        procesarNumero("9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
       
        procesarNumero("4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
       
        procesarNumero("5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
     
        procesarNumero("6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
     
        procesarNumero("1");
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
   
        procesarNumero("2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        
        procesarNumero("3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
      
        procesarNumero("0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
         procesarOperador("/");
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicacionActionPerformed
 procesarOperador("*");
    }//GEN-LAST:event_btn_multiplicacionActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        procesarOperador("-");
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
         procesarOperador("+");
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultadoActionPerformed
procesarResultado();
    }//GEN-LAST:event_btn_resultadoActionPerformed
    private void procesarOperador(String nuevoOperador) {

        //si no hay ningun numero escrito
        if (entradaActual.isEmpty()) {
            //si ya existe un operador solamente lo reemplazamos
            if (!operador.isEmpty()) {
                operador = nuevoOperador;

            }
            return;
        }
        
        //Convertimos el nmero que el usuario escribio 
        double numeroActual= Double.parseDouble(entradaActual);
        
        //si es el prmer operador
        if(operador.isEmpty()){
            acumulado=numeroActual;
        }else{
            //Ejecutamos el operador que etaba pendiente
            switch(operador){
                case "+" -> acumulado=acumulado+numeroActual;
                case "-" -> acumulado=acumulado-numeroActual;
                case "*" -> acumulado=acumulado*numeroActual;
                case "/" -> {
                    if(numeroActual==0){
                        txt_Visor.setText("Error : Division entre cero");
                        return;
                        
                    }
                    
                    acumulado=acumulado/numeroActual;
                }
            }
        }
        
        operador=nuevoOperador;
        
        //preapramos la escritura del siguiente numero
        entradaActual="";
        bandera=true;
        
        //imprimimios el acumulado
      txt_Visor.setText(formatearNumero(acumulado));
    }
    private void procesarResultado() {

    // No hay operación pendiente
    if (operador.isEmpty()) {
        return;
    }

    // Todavía no se escribió el segundo número
    if (entradaActual.isEmpty()) {
        return;
    }

    double numeroActual = Double.parseDouble(entradaActual);

    switch (operador) {

        case "+" -> acumulado = acumulado + numeroActual;

        case "-" -> acumulado = acumulado - numeroActual;

        case "*" -> acumulado = acumulado * numeroActual;

        case "/" -> {
            if (numeroActual == 0) {
                txt_Visor.setText("Error: división entre cero");

                acumulado = 0.0;
                entradaActual = "";
                operador = "";
                bandera = true;

                return;
            }

            acumulado = acumulado / numeroActual;
        }
    }

    txt_Visor.setText(formatearNumero(acumulado));

    // Conservamos el resultado para poder seguir operando
    entradaActual = Double.toString(acumulado);

    // Ya no queda ninguna operación pendiente
    operador = "";

    // El siguiente número comenzará una operación nueva
    bandera = true;
}
    private String formatearNumero(double numero) {

    if (numero == Math.rint(numero)) {
        return Long.toString((long) numero);
    }

    return Double.toString(numero);
}
    private void btn_7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_7KeyPressed

    private void procesarNumero(String numeroPresionado){
        if(bandera==true){
            entradaActual=numeroPresionado;
            bandera=false;
        }
        else{
            entradaActual+=numeroPresionado;
            
        }
        txt_Visor.setText(entradaActual);
    }
    
    private void asociarTecla(
        String nombreAccion,
        KeyStroke tecla,
        JButton boton
) {
    getRootPane()
            .getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
            .put(tecla, nombreAccion);

    getRootPane()
            .getActionMap()
            .put(nombreAccion, new AbstractAction() {
                
                @Override
                public void actionPerformed(ActionEvent e) {
                    boton.doClick();
                }
            });
}
    
    private void configurarTeclado() {

    // Números de la fila superior
    asociarTecla("numero0", KeyStroke.getKeyStroke('0'), btn_0);
    asociarTecla("numero1", KeyStroke.getKeyStroke('1'), btn_1);
    asociarTecla("numero2", KeyStroke.getKeyStroke('2'), btn_2);
    asociarTecla("numero3", KeyStroke.getKeyStroke('3'), btn_3);
    asociarTecla("numero4", KeyStroke.getKeyStroke('4'), btn_4);
    asociarTecla("numero5", KeyStroke.getKeyStroke('5'), btn_5);
    asociarTecla("numero6", KeyStroke.getKeyStroke('6'), btn_6);
    asociarTecla("numero7", KeyStroke.getKeyStroke('7'), btn_7);
    asociarTecla("numero8", KeyStroke.getKeyStroke('8'), btn_8);
    asociarTecla("numero9", KeyStroke.getKeyStroke('9'), btn_9);

    // Operadores del teclado normal
    asociarTecla("suma", KeyStroke.getKeyStroke('+'), btn_suma);
    asociarTecla("resta", KeyStroke.getKeyStroke('-'), btn_resta);
    asociarTecla(
            "multiplicacion",
            KeyStroke.getKeyStroke('*'),
            btn_multiplicacion
    );
    asociarTecla(
            "division",
            KeyStroke.getKeyStroke('/'),
            btn_division
    );

    // Resultado
    asociarTecla(
            "igual",
            KeyStroke.getKeyStroke('='),
            btn_resultado
    );

    asociarTecla(
            "enter",
            KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),
            btn_resultado
    );

    // Limpiar calculadora
    asociarTecla(
            "escape",
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
            btn_c
    );
    
    
    asociarTecla(
        "numpad0",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD0, 0),
        btn_0
);

asociarTecla(
        "numpad1",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD1, 0),
        btn_1
);

asociarTecla(
        "numpad2",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD2, 0),
        btn_2
);

asociarTecla(
        "numpad3",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD3, 0),
        btn_3
);

asociarTecla(
        "numpad4",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD4, 0),
        btn_4
);

asociarTecla(
        "numpad5",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD5, 0),
        btn_5
);

asociarTecla(
        "numpad6",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD6, 0),
        btn_6
);

asociarTecla(
        "numpad7",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD7, 0),
        btn_7
);

asociarTecla(
        "numpad8",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD8, 0),
        btn_8
);

asociarTecla(
        "numpad9",
        KeyStroke.getKeyStroke(KeyEvent.VK_NUMPAD9, 0),
        btn_9
);

asociarTecla(
        "sumaNumpad",
        KeyStroke.getKeyStroke(KeyEvent.VK_ADD, 0),
        btn_suma
);

asociarTecla(
        "restaNumpad",
        KeyStroke.getKeyStroke(KeyEvent.VK_SUBTRACT, 0),
        btn_resta
);

asociarTecla(
        "multiplicacionNumpad",
        KeyStroke.getKeyStroke(KeyEvent.VK_MULTIPLY, 0),
        btn_multiplicacion
);

asociarTecla(
        "divisionNumpad",
        KeyStroke.getKeyStroke(KeyEvent.VK_DIVIDE, 0),
        btn_division
);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pantalla().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_multiplicacion;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_resultado;
    private javax.swing.JButton btn_suma;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_Visor;
    // End of variables declaration//GEN-END:variables
}
